FROM scratch
ADD centos-stream-9-ppc64le.tar.xz /
ADD development.repo /etc/yum.repos.d/
LABEL org.label-schema.schema-version="1.0"     org.label-schema.name="CentOS Stream 9 Base Image"     org.label-schema.vendor="CentOS"     org.label-schema.license="GPLv2"     org.label-schema.build-date="20210615"
CMD ["/bin/bash"]
